apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: it8e2okft-nodejs
  janus-idp.io/tekton: it8e2okft-nodejs
  backstage.io/kubernetes-id: it8e2okft-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: it8e2okft-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
