apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: it8e2okft-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: it8e2okft-nodejs 
  name: it8e2okft-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: it8e2okft-nodejs 
